import type { Metadata } from 'next'
import { Alice, Open_Sans as OpenSans } from '@next/font/google'

import { Analytics } from '@vercel/analytics/react'

import { NavBar } from '@/components/NavBar'
import { Footer } from '@/components/Footer'

import './globals.css'

export const metadata: Metadata = {
  title: 'The Brand Boost',
  description: 'Generated by create next app',
}

type RootLayoutProps = {
  children: React.ReactNode
}

const alice = Alice({ weight: '400', subsets: ['latin'], variable: '--font-alice' })
const opensSans = OpenSans({ weight: ['400', '700'], subsets: ['latin'], variable: '--font-open-sans' })

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang='en' className='overflow-x-clip'>
      <body className={`${alice.variable} ${opensSans.variable} font-sans relative overflow-x-clip`}>
        <NavBar />
        <main>{children}</main>
        <Footer />
        <Analytics />
      </body>
    </html>
  )
}
